language: python

python:
  - 3.5
install:
  - pip install tox
  - pip install tox-travis

script:
  - tox

jobs:
  include:
    - stage: flake
      python: 3.5
      script:
        - tox -e flake8
        - tox -e py35 
tags: true
