language: python

python:
  - 3.5
install:
  - pip install tox
  - pip install tox-travis

script:
  - tox

jobs:
  include:
    - stage: flake
      python: 3.5
      script:
        - tox -e flake8

    - stage: python 3.5 tests
      python: 3.5
      script:
        - tox -e py35

    - stage: python 3.6 tests
      python: 3.6
      script:
        - tox -e py36

    - stage: python 3.7 tests
      python: 3.7
      dist: xenial
      sudo: true
      script:
        - tox -e py37

tags: true
